---
title: "Data_Import"
output: github_document
date: 09/19/2020
---

```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

## Read in some data

Read in the litters dataset.

```{r}
litters_df = read_csv("./data_import_examples/fas_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## Take a look at the data

Printing in the console.

```{r}
litters_df #checking the first 10 rows
```

```{r}
head(litters_df) #check first 6 rows
tail(litters_df) #check last 6 rows
```

```{r}
skimr::skim(litters_df)
```

## Options to read_csv

Check out `?read_csv` for more information.
```{r}
litters_df = read_csv("./data_import_examples/fas_litters.csv", skip = 10, col_names = FALSE)
litters_df = read_csv("./data_import_examples/fas_litters.csv", na = c("", "NA", 999)) #values in this list will be considered missing
```

## Other file formats

Read in an excel file.

```{r}
mlb_df = read_excel("./data_import_examples/mlb11.xlsx")
mlb_df
```

Read in a SAS file.

```{r}
pulse_df = read_sas("./data_import_examples/public_pulse_data.sas7bdat")
pulse_df
```

## Comparison with Base R

What about `read.csv` (built in R)?

```{r}
litters_base = read.csv("./data_import_examples/fas_litters.csv")
litters_readr = read_csv ("./data_import_examples/fas_litters.csv")

litters_base
litters_readr
```

