---
title: "Data_Manipulation"
output: github_document
date: 09/20/2020
---

```{r setup}
library(tidyverse)
```

## Load the fas_litters data

```{r}
litters_df = read_csv("./data_import_examples/fas_litters.csv")
litters_df = janitor ::clean_names(litters_df)
```

## `select`

Choose some columns and not others

```{r}
select(litters_df, group, gd0_weight)
```

```{r}
select(litters_df, group, gd0_weight:gd_of_birth) #range of columns first:last
```

```{r}
select(litters_df, -litter_number) #removes specific column
```

Renaming columns

```{r}
select(litters_df, GROUP = group, gd0_weight) #there is a specific function - rename() for this!
rename(litters_df, GROUP = group)
```

Select helpers

```{r}
select(litters_df, starts_with("gd")) #you can mix:
select(litters_df, group, starts_with("gd"))
```

```{r}
select(litters_df, litter_number, everything()) # the everything brings everything, but also EVERYTHING ELSE
```
Same thing as...
```{r}
relocate(litters_df, gd_of_birth)
```

## `filter`

```{r}
filter(litters_df, gd0_weight < 22)
```

```{r}
filter(litters_df, gd0_weight >= 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, !(gd_of_birth == 20)) #"not equal to" 20
filter(litters_df, gd_of_birth != 20) #equivalent 
```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth ==20) #AND
```

```{r}
filter(litters_df, group == "Mod8")
```

```{r}
filter(litters_df, group %in% c("Con7", "Mod8")) #OR
```

## `mutate``

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)
#tidy up!

mutate(
  litters_df,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group) #made the group variable have al lower case characters!
)
```

## `arrange`

```{r}
arrange(litters_df, pups_born_alive)
arrange(litters_df, pups_born_alive, gd0_weight)
```

## `%>%`

```{r}
# not efficient
litters_data_raw = read_csv("./data_import_examples/fas_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_raw)
litters_data_selected = select(litters_clean_name, -pups_survive)
litters_mutated = mutate(litters_data_selected, wt_gain = gd18_weight - gd0_weight)
litters_without_missing = drop_na(litters_mutated, gd0_weight) #if you dont specify it drops all NAs
```

USE THE PIPE OPERATOR INSTEAD!

```{r}
litters_df = 
  read_csv("./data_import_examples/fas_litters.csv") %>% #shit + cmd + m
  janitor::clean_names() %>% 
  select(-pups_survive) %>% #the previous result is the first argument - dont need to write
  mutate(wt_gain = gd18_weight - gd0_weight) %>% 
  drop_na(gd0_weight)
```

